import type { User, Subject, Resource, ExamType } from "./types"

export const MOCK_USERS: User[] = [
  {
    id: "student1",
    username: "john_student",
    password: "student123",
    role: "student",
    grade: 11,
    targetExam: "JEE",
    createdAt: new Date(),
  },
  {
    id: "student2",
    username: "priya_student",
    password: "student456",
    role: "student",
    grade: 12,
    targetExam: "NEET",
    createdAt: new Date(),
  },
  {
    id: "admin1",
    username: "admin_user",
    password: "admin123",
    role: "admin",
    createdAt: new Date(),
  },
]

export const EXAM_SUBJECTS: Record<ExamType, Subject[]> = {
  CBSE: [
    { id: "s1", name: "Mathematics", grade: 10, examType: "CBSE", weightage: 25, totalQuestions: 30 },
    { id: "s2", name: "Physics", grade: 10, examType: "CBSE", weightage: 25, totalQuestions: 25 },
    { id: "s3", name: "Chemistry", grade: 10, examType: "CBSE", weightage: 25, totalQuestions: 25 },
    { id: "s4", name: "Biology", grade: 10, examType: "CBSE", weightage: 25, totalQuestions: 25 },
  ],
  ICSE: [
    { id: "s5", name: "Mathematics", grade: 10, examType: "ICSE", weightage: 20, totalQuestions: 35 },
    { id: "s6", name: "Physics", grade: 10, examType: "ICSE", weightage: 20, totalQuestions: 30 },
    { id: "s7", name: "Chemistry", grade: 10, examType: "ICSE", weightage: 20, totalQuestions: 30 },
    { id: "s8", name: "Biology", grade: 10, examType: "ICSE", weightage: 20, totalQuestions: 30 },
    { id: "s9", name: "English", grade: 10, examType: "ICSE", weightage: 20, totalQuestions: 20 },
  ],
  JEE: [
    { id: "s10", name: "Physics", grade: 12, examType: "JEE", weightage: 33, totalQuestions: 20 },
    { id: "s11", name: "Chemistry", grade: 12, examType: "JEE", weightage: 33, totalQuestions: 20 },
    { id: "s12", name: "Mathematics", grade: 12, examType: "JEE", weightage: 34, totalQuestions: 25 },
  ],
  NEET: [
    { id: "s13", name: "Physics", grade: 12, examType: "NEET", weightage: 25, totalQuestions: 45 },
    { id: "s14", name: "Chemistry", grade: 12, examType: "NEET", weightage: 25, totalQuestions: 45 },
    { id: "s15", name: "Biology", grade: 12, examType: "NEET", weightage: 50, totalQuestions: 90 },
  ],
  SAT: [
    { id: "s16", name: "Reading & Writing", grade: 11, examType: "SAT", weightage: 50, totalQuestions: 52 },
    { id: "s17", name: "Math", grade: 11, examType: "SAT", weightage: 50, totalQuestions: 58 },
  ],
  IB: [
    { id: "s18", name: "Mathematics", grade: 12, examType: "IB", weightage: 20, totalQuestions: 40 },
    { id: "s19", name: "Physics", grade: 12, examType: "IB", weightage: 20, totalQuestions: 40 },
    { id: "s20", name: "Chemistry", grade: 12, examType: "IB", weightage: 20, totalQuestions: 40 },
    { id: "s21", name: "Biology", grade: 12, examType: "IB", weightage: 20, totalQuestions: 40 },
  ],
  Olympiad: [
    { id: "s22", name: "Mathematics Olympiad", grade: 10, examType: "Olympiad", weightage: 50, totalQuestions: 30 },
    { id: "s23", name: "Science Olympiad", grade: 10, examType: "Olympiad", weightage: 50, totalQuestions: 50 },
  ],
}

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "r1",
    type: "video",
    title: "Quadratic Equations - Complete Tutorial",
    subjectId: "s1",
    topic: "Quadratic Equations",
    difficulty: "medium",
    url: "https://youtube.com/embed/dQw4w9WgXcQ",
    description: "Comprehensive video on solving quadratic equations with examples",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "r2",
    type: "pdf",
    title: "Algebra Notes - Fundamentals",
    subjectId: "s1",
    topic: "Algebra",
    difficulty: "easy",
    fileUrl: "/resources/algebra-notes.pdf",
    description: "Core algebra concepts and formulas",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "r3",
    type: "question",
    title: "Previous Year Mathematics Questions (2023)",
    subjectId: "s1",
    topic: "Geometry",
    difficulty: "hard",
    fileUrl: "/resources/math-2023.pdf",
    description: "CBSE Mathematics board exam previous year questions",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "r4",
    type: "video",
    title: "Atoms & Molecular Structure",
    subjectId: "s3",
    topic: "Atomic Structure",
    difficulty: "medium",
    url: "https://youtube.com/embed/dQw4w9WgXcQ",
    description: "Deep dive into atomic theory and electron configuration",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "r5",
    type: "pdf",
    title: "Chemical Reactions & Equations",
    subjectId: "s3",
    topic: "Chemical Reactions",
    difficulty: "easy",
    fileUrl: "/resources/chemistry-basics.pdf",
    description: "Introduction to chemical equations and balancing",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "r6",
    type: "question",
    title: "Physics Previous Papers (2023-2024)",
    subjectId: "s2",
    topic: "Mechanics",
    difficulty: "hard",
    fileUrl: "/resources/physics-papers.pdf",
    description: "Board exam previous year physics questions",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "r7",
    type: "video",
    title: "Motion & Forces Explained",
    subjectId: "s2",
    topic: "Mechanics",
    difficulty: "easy",
    url: "https://youtube.com/embed/dQw4w9WgXcQ",
    description: "Fundamental concepts of motion and Newton's laws",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "r8",
    type: "video",
    title: "JEE Mathematics - Advanced Algebra",
    subjectId: "s12",
    topic: "Algebra",
    difficulty: "hard",
    url: "https://youtube.com/embed/dQw4w9WgXcQ",
    description: "Competitive level algebra problems for JEE preparation",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
