import type { Subject, Resource, Quiz } from "./types"

export const mockSubjects: Subject[] = [
  // School Board Subjects (CBSE/ICSE) - Grades 1-12
  {
    id: "math-board",
    name: "Mathematics",
    examBoard: "CBSE",
    examType: "CBSE",
    category: "board",
    examWeightage: 30,
    topics: [
      { id: "numbers", name: "Number System", subjectId: "math-board", difficulty: "beginner", order: 1 },
      { id: "algebra", name: "Algebra", subjectId: "math-board", difficulty: "intermediate", order: 2 },
      { id: "geometry", name: "Geometry", subjectId: "math-board", difficulty: "intermediate", order: 3 },
      { id: "calculus", name: "Calculus", subjectId: "math-board", difficulty: "advanced", order: 4 },
    ],
  },
  {
    id: "science-board",
    name: "Science",
    examBoard: "CBSE",
    examType: "CBSE",
    category: "board",
    examWeightage: 25,
    topics: [
      { id: "biology", name: "Biology", subjectId: "science-board", difficulty: "beginner", order: 1 },
      { id: "chemistry", name: "Chemistry", subjectId: "science-board", difficulty: "intermediate", order: 2 },
      { id: "physics", name: "Physics", subjectId: "science-board", difficulty: "intermediate", order: 3 },
    ],
  },
  {
    id: "english-board",
    name: "English",
    examBoard: "CBSE",
    examType: "CBSE",
    category: "board",
    examWeightage: 15,
    topics: [
      { id: "grammar", name: "Grammar", subjectId: "english-board", difficulty: "beginner", order: 1 },
      { id: "literature", name: "Literature", subjectId: "english-board", difficulty: "intermediate", order: 2 },
    ],
  },

  // JEE Main Subjects
  {
    id: "math-jee",
    name: "Mathematics",
    examBoard: "JEE",
    examType: "JEE Main",
    category: "competitive",
    examWeightage: 33,
    topics: [
      { id: "sets", name: "Sets & Relations", subjectId: "math-jee", difficulty: "beginner", order: 1 },
      { id: "complex", name: "Complex Numbers", subjectId: "math-jee", difficulty: "intermediate", order: 2 },
      { id: "matrices", name: "Matrices & Determinants", subjectId: "math-jee", difficulty: "intermediate", order: 3 },
      { id: "calculus-jee", name: "Calculus", subjectId: "math-jee", difficulty: "advanced", order: 4 },
      { id: "vectors", name: "Vectors & 3D", subjectId: "math-jee", difficulty: "advanced", order: 5 },
    ],
  },
  {
    id: "physics-jee",
    name: "Physics",
    examBoard: "JEE",
    examType: "JEE Main",
    category: "competitive",
    examWeightage: 33,
    topics: [
      { id: "mechanics", name: "Mechanics", subjectId: "physics-jee", difficulty: "beginner", order: 1 },
      { id: "heat", name: "Thermodynamics", subjectId: "physics-jee", difficulty: "intermediate", order: 2 },
      { id: "waves", name: "Waves & Sound", subjectId: "physics-jee", difficulty: "intermediate", order: 3 },
      {
        id: "electricity",
        name: "Electricity & Magnetism",
        subjectId: "physics-jee",
        difficulty: "advanced",
        order: 4,
      },
      { id: "modern", name: "Modern Physics", subjectId: "physics-jee", difficulty: "advanced", order: 5 },
    ],
  },
  {
    id: "chemistry-jee",
    name: "Chemistry",
    examBoard: "JEE",
    examType: "JEE Main",
    category: "competitive",
    examWeightage: 34,
    topics: [
      {
        id: "inorganic",
        name: "Inorganic Chemistry",
        subjectId: "chemistry-jee",
        difficulty: "intermediate",
        order: 1,
      },
      { id: "organic", name: "Organic Chemistry", subjectId: "chemistry-jee", difficulty: "intermediate", order: 2 },
      { id: "physical", name: "Physical Chemistry", subjectId: "chemistry-jee", difficulty: "advanced", order: 3 },
    ],
  },

  // NEET Subjects
  {
    id: "biology-neet",
    name: "Biology",
    examBoard: "NEET",
    examType: "NEET",
    category: "competitive",
    examWeightage: 50,
    topics: [
      { id: "cell", name: "Cell Biology", subjectId: "biology-neet", difficulty: "beginner", order: 1 },
      { id: "genetics", name: "Genetics", subjectId: "biology-neet", difficulty: "intermediate", order: 2 },
      { id: "ecology", name: "Ecology & Evolution", subjectId: "biology-neet", difficulty: "intermediate", order: 3 },
      { id: "human", name: "Human Physiology", subjectId: "biology-neet", difficulty: "advanced", order: 4 },
    ],
  },
  {
    id: "physics-neet",
    name: "Physics",
    examBoard: "NEET",
    examType: "NEET",
    category: "competitive",
    examWeightage: 25,
    topics: [
      { id: "mechanics-neet", name: "Mechanics", subjectId: "physics-neet", difficulty: "beginner", order: 1 },
      { id: "waves-neet", name: "Waves & Sound", subjectId: "physics-neet", difficulty: "intermediate", order: 2 },
      { id: "electricity-neet", name: "Electricity", subjectId: "physics-neet", difficulty: "intermediate", order: 3 },
    ],
  },
  {
    id: "chemistry-neet",
    name: "Chemistry",
    examBoard: "NEET",
    examType: "NEET",
    category: "competitive",
    examWeightage: 25,
    topics: [
      {
        id: "inorganic-neet",
        name: "Inorganic Chemistry",
        subjectId: "chemistry-neet",
        difficulty: "intermediate",
        order: 1,
      },
      {
        id: "organic-neet",
        name: "Organic Chemistry",
        subjectId: "chemistry-neet",
        difficulty: "intermediate",
        order: 2,
      },
    ],
  },
]

export const mockResources: Resource[] = [
  // Mathematics Board
  {
    id: "vid-math-1",
    type: "video",
    title: "Algebra Fundamentals",
    topicId: "algebra",
    subjectId: "math-board",
    description: "Learn the basics of algebra with clear examples",
    url: "https://www.youtube.com/embed/NybHckSEQq4",
    difficulty: "beginner",
    thumbnail: "/calculus-lesson.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "note-math-1",
    type: "note",
    title: "Algebra Study Notes",
    topicId: "algebra",
    subjectId: "math-board",
    description: "Comprehensive algebra concepts and formulas",
    url: "/resources/algebra-notes.pdf",
    difficulty: "beginner",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "paper-math-1",
    type: "paper",
    title: "Board Exam Paper 2023",
    topicId: "algebra",
    subjectId: "math-board",
    description: "Previous year question paper with solutions",
    url: "/resources/board-math-2023.pdf",
    difficulty: "intermediate",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Physics - JEE Main
  {
    id: "vid-physics-jee-1",
    type: "video",
    title: "Mechanics - Laws of Motion",
    topicId: "mechanics",
    subjectId: "physics-jee",
    description: "Newton's laws of motion explained with examples",
    url: "https://www.youtube.com/embed/UL6-VdquaIk",
    difficulty: "beginner",
    thumbnail: "/physics-mechanics-diagram.png",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "note-physics-jee-1",
    type: "note",
    title: "Mechanics Complete Notes",
    topicId: "mechanics",
    subjectId: "physics-jee",
    description: "Detailed mechanics concepts for JEE",
    url: "/resources/jee-mechanics.pdf",
    difficulty: "intermediate",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "paper-physics-jee-1",
    type: "paper",
    title: "JEE Main 2023 - Physics Paper",
    topicId: "mechanics",
    subjectId: "physics-jee",
    description: "Official JEE Main question paper with solutions",
    url: "/resources/jee-main-2023-physics.pdf",
    difficulty: "advanced",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Chemistry - JEE Main
  {
    id: "vid-chem-jee-1",
    type: "video",
    title: "Organic Chemistry Basics",
    topicId: "organic",
    subjectId: "chemistry-jee",
    description: "Introduction to organic chemistry mechanisms",
    url: "https://www.youtube.com/embed/WUvTyaaNkzM",
    difficulty: "beginner",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "note-chem-jee-1",
    type: "note",
    title: "Organic Chemistry Reactions",
    topicId: "organic",
    subjectId: "chemistry-jee",
    description: "Key reactions and mechanisms for JEE",
    url: "/resources/jee-organic-reactions.pdf",
    difficulty: "intermediate",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "paper-chem-jee-1",
    type: "paper",
    title: "JEE Advanced 2022 - Chemistry",
    topicId: "organic",
    subjectId: "chemistry-jee",
    description: "Advanced level chemistry problems",
    url: "/resources/jee-advanced-2022-chem.pdf",
    difficulty: "advanced",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Biology - NEET
  {
    id: "vid-bio-neet-1",
    type: "video",
    title: "Cell Structure and Function",
    topicId: "cell",
    subjectId: "biology-neet",
    description: "Detailed study of cell organelles",
    url: "https://www.youtube.com/embed/URUJD5NEXC8",
    difficulty: "beginner",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "note-bio-neet-1",
    type: "note",
    title: "Cell Biology Complete Guide",
    topicId: "cell",
    subjectId: "biology-neet",
    description: "Comprehensive notes on cell biology",
    url: "/resources/neet-cell-biology.pdf",
    difficulty: "intermediate",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "paper-bio-neet-1",
    type: "paper",
    title: "NEET 2023 - Official Paper",
    topicId: "cell",
    subjectId: "biology-neet",
    description: "Complete NEET exam question paper with solutions",
    url: "/resources/neet-2023-official.pdf",
    difficulty: "advanced",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockQuizzes: Quiz[] = [
  {
    id: "quiz-algebra",
    title: "Algebra Basics",
    topicId: "algebra",
    difficulty: "beginner",
    questions: [
      {
        id: "q1",
        question: "Solve: 2x + 5 = 13",
        options: ["x = 4", "x = 9", "x = 6", "x = 3"],
        correctAnswer: 0,
        explanation: "2x + 5 = 13 → 2x = 8 → x = 4",
      },
      {
        id: "q2",
        question: "What is (a + b)²?",
        options: ["a² + b²", "a² + 2ab + b²", "a² - 2ab + b²", "2a + 2b"],
        correctAnswer: 1,
        explanation: "(a + b)² = a² + 2ab + b² (binomial expansion)",
      },
    ],
  },
  {
    id: "quiz-mechanics",
    title: "Mechanics Challenge",
    topicId: "mechanics",
    difficulty: "intermediate",
    questions: [
      {
        id: "q3",
        question: "Newton's second law states: F = ?",
        options: ["m/a", "ma", "m+a", "m-a"],
        correctAnswer: 1,
        explanation: "Force equals mass times acceleration: F = ma",
      },
    ],
  },
  {
    id: "quiz-biology",
    title: "Cell Biology Basics",
    topicId: "cell",
    difficulty: "beginner",
    questions: [
      {
        id: "q4",
        question: "Which is the powerhouse of the cell?",
        options: ["Nucleus", "Mitochondria", "Ribosome", "Chloroplast"],
        correctAnswer: 1,
        explanation: "Mitochondria is known as the powerhouse of the cell as it produces ATP energy",
      },
    ],
  },
]
